# Generated by Django 3.1.1 on 2020-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
