# Generated by Django 3.1.1 on 2020-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200908_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('perm_address', models.CharField(max_length=100)),
                ('temp_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('provinces', models.CharField(choices=[('1', 'State 1'), ('2', 'State 2'), ('3', 'State 3'), ('4', 'State 4'), ('5', 'State 5'), ('6', 'State 6'), ('7', 'State 7')], max_length=50)),
                ('cover_letter', models.TextField(default=None, max_length=500)),
                ('cv', models.FileField(default=1, max_length=250, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
