# Generated by Django 3.1.1 on 2020-09-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200908_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_letter',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
