# Generated by Django 3.1.1 on 2020-09-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200913_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='perm_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='work',
            name='provinces',
        ),
        migrations.RemoveField(
            model_name='work',
            name='temp_address',
        ),
    ]
