# Generated by Django 3.1.1 on 2020-09-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200919_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='cover_letter',
            new_name='letter',
        ),
    ]
